Feature/tasks
spikers-dev/TaskManagerUP pull request #14
Opened 2022-10-15 17:56 UTC by spikers-dev

Тесты починились) всё работает.
Я убрал в контроллере Task.all, поставив сразу запрос ransack, и отклик уменьшился с 6000ms до 1400, дальше по обучению может поломаться что-то от такого действия? или в принципе это очередная "ошибка"? Иногда мозг плавиться от раздумий стоит что-либо менять или нет, сделаешь хорошо или потом искать где сам поломал)

2022-10-16 14:37 UTC, greybutton requested changes
> дальше по обучению может поломаться что-то от такого действия?

не должно

> ui/ux оценивается?

нет, можешь как хочешь сделать

2022-10-16 14:37 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +      order(id: :desc).
почему задал ордер? можно в рансак параметрах передать и это предпочитаемый вариант

2022-10-16 14:37 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import ColumnHeader from '../ColumnHeader';
from 'components/ColumnHeader

2022-10-16 14:37 UTC, greybutton commented on app/javascript/components/TaskBoard/TaskBoard.js
> +import useStyles from './useStyles';
смешались импорты, сначала внешние пакеты, потом локальные файлы

2022-10-16 14:37 UTC, greybutton commented on app/javascript/utils/fetchHelper.js
> +    return axios.delete(url, body).then(camelize);
у делете обычно нет боди

2022-10-16 16:36 UTC, spikers-dev commented
> > дальше по обучению может поломаться что-то от такого действия?
> 
> не должно

Значит я правильно понял что он всю таблицу извлекает, что не совсем хорошо по производительности...

2022-10-17 06:47 UTC, greybutton approved these changes

2022-10-17 09:53 UTC, merged