add developers
spikers-dev/TaskManagerUP pull request #7
Opened 2022-10-06 15:56 UTC by spikers-dev

Я надеюсь сюда можно писать вопросы, или в чат общий? они специфичные)
Я же верно делал что создал developers командой  rails g controller Web::Developers new --no-assets --no-helper ? там явно не указано в задании.
Сразу прописывает неймспес в роуты, я пока закомментировал (знаю что нельзя), это убрать или оставить?
И в ссылке про хелперы явно указано @current_user ||= User.find_by_id(session[:user]), а не @_current_user,  ну и рубокоп ругается, поправил.

2022-10-06 16:30 UTC, greybutton requested changes
сюда можно да

команда валидная, просто не всегда используется, то что рельса генерирует) поэтому надо оставить resources

про хелперы ок, а тесты проходят?

2022-10-06 18:23 UTC, spikers-dev commented
This error is raised because the column 'type' is reserved for storing the class in case of inheritance.
Поменять класс колонки?

2022-10-06 19:18 UTC, spikers-dev commented
Всё открывается, борд работает. 10 из 11 тестов проходят.
test_should_post_create: сейчас искать почему не проходит?

2022-10-06 20:50 UTC, spikers-dev commented
Всё открывается, борд работает. 10 из 11 тестов проходят.
test_should_post_create:  не должен вроде проходить

2022-10-07 08:01 UTC, greybutton requested changes
> [Merge branch 'develop' into feature/user](https://github.com/spikers-dev/TaskManagerUP/pull/7/commits/d0ba11e921c04b5e96591274cbe3750bdcc50c73)

таких коммитов быть не должно, если нужно поднять изменения из девелопа, то делается пулл с ребейсом девелопа, переключение в ветку, ребейс ветки от девелопа

2022-10-07 11:51 UTC, spikers-dev commented
Надеюсь так правильно. По поводу изменений запомнил, записал)

2022-10-07 12:01 UTC, spikers-dev commented
Надеюсь так правильно. По поводу изменений запомнил, записал.

2022-10-07 15:44 UTC, greybutton approved these changes
я аппрувулю, но у тебя конфликты гитхаб пишет. их надо зарезолвить перед мерджем

2022-10-07 15:45 UTC, greybutton commented on config/routes.rb
> -    resource :board, only: :show
это не надо удалять

2022-10-07 16:22 UTC, merged